name: offline_error_logger
description: Offline-first error logger with Telegram reporter for Flutter apps.
version: 1.0.0

homepage: https://github.com/ITACHI-oss/offline_error_logger.git
repository: https://github.com/ITACHI-oss/offline_error_logger.git
issue_tracker: https://github.com/ITACHI-oss/offline_error_logger/issues

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  http: ^1.2.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
